version: '2.1'
services:
  apache-pulsar:
    image: haritkumar/apache-pulsar:2.4.0
    ports:
      - '8080:8080'
      - '6650:6650'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/admin/v2/persistent/public/default"]
        interval: 30s
        timeout: 10s
        retries: 5  
    networks:
      - pulsarnet
  pulsar-client:
    image: haritkumar/pulsar-client:latest
    depends_on:
      apache-pulsar:
        condition: service_healthy
    ports:
      - '9000:9000'
    networks:
      - pulsarnet  
  pulsar-express:
    image: haritkumar/pulsar-express:latest
    depends_on:
      apache-pulsar:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
        - PE_CONNECTION_URL=http://apache-pulsar:8080  
        - PE_CONNECTION_NAME=test-cluster
    networks:
      - pulsarnet      

networks:
  pulsarnet:      