FROM ubuntu:16.04

RUN apt-get update -y && apt-get install -y wget curl
RUN wget -qO- https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs && apt-get clean

RUN npm install pulsar-express -g
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
EXPOSE 3000
CMD ["pulsar-express"]   
