FROM ubuntu:16.04

RUN apt-get update -y && apt-get install -y wget
RUN wget -qO- https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs && apt-get clean

RUN npm install pulsar-express -g
ENV PE_CONNECTION_URL=http://apache-pulsar:8080
ENV PE_CONNECTION_NAME=apache-pulsar
EXPOSE 3000
CMD ["pulsar-express"]   
